routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'AuthController@viewLoginPage')->name('login');
Route::post('login', 'AuthController@authenticate')->name('authenticate');
Route::get('logout', 'AuthController@logout')->name('logout');

Route::middleware(['admin'])->group(function () {
    Route::get('profile', 'ProfileController@profile')->name('profile');
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::resource('school_info', 'SchoolController');
    Route::resource('admins', 'AdminController');
    Route::resource('academic_years', 'AcademicYearController');
    Route::resource('school_grades', 'SchoolGradeController');
    Route::resource('class_rooms', 'ClassRoomController');
    Route::resource('sections', 'SectionController');
    Route::get('section/{id}', 'SectionController@ajaxSelection');
    Route::resource('students', 'StudentController');
    Route::post('students/payment', 'StudentController@payment')->name('students.payment');
    Route::get('students/payment/receipt/{id}', 'StudentController@payment_receipt')->name('students.payment_receipt');
    Route::post('students/attachment', 'StudentController@attachment')->name('students.attachment');
    Route::post('students/transfer', 'StudentController@transfer')->name('students.transfer');
    Route::resource('category_expenses', 'CategoryExpensesController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('agreements', 'AgreementController');
    Route::get('agreements/getClassRoomPrice/{id}', 'AgreementController@getClassRoomPrice');

    Route::prefix('reports')->name('reports.')->group(function (){
        Route::get('payments', 'ReportController@payments')->name('payments');
        Route::get('payments/receipt/{id}', 'ReportController@payments_receipt')->name('payments.receipt');
        Route::get('expenses', 'ReportController@expenses')->name('expenses');
        Route::get('expenses/receipt/{id}', 'ReportController@expenses_receipt')->name('expenses.receipt');
        Route::get('agreements', 'ReportController@agreements')->name('agreements');
    });

    Route::prefix('employees')->name('employees.')->group(function(){
        Route::resource('sections', 'EmployeeSectionController');
        Route::resource('jobs', 'EmployeeJobController');
        Route::resource('salaries', 'EmployeeSalaryController');
        Route::resource('agreements', 'EmployeeAgreementController');
        Route::resource('allowances', 'EmployeeAllowanceController');
        Route::resource('incentives', 'EmployeeIncentiveController');
        Route::resource('discounts', 'EmployeeDiscountController');
    });
    Route::resource('employees', 'EmployeeController');

    Route::prefix('categories')->name('categories.')->group(function(){
        Route::resource('allowances', 'CategoryAllowanceController');
        Route::resource('incentives', 'CategoryIncentiveController');
        Route::resource('discounts', 'CategoryDiscountController');
    });

    Route::get('set-locale/{locale}', function ($scope, $locale) {
        session()->put('locale', $locale);
        return redirect()->back();
    })->name('locale.setting');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = [];
}

resources/views/Admin/employees/categories/discounts/index.blade.php
@extends('Admin.layouts.app')
@section('title') {{__('admin.categoryDiscoSideBar')}} @endsection
@section('content')

    <div class="br-pageheader">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <span class="breadcrumb-item active">{{__('admin.categoryDiscoSideBar')}}</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="br-pagetitle">

    </div><!-- d-flex -->
    <!-- Button trigger modal -->
    @if(auth()->guard('admin')->user()->hasPermissionTo('create category discount'))
    <div style="padding:15px;float: right">
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#addCategoryDiscount">
            <i class="fa fa-plus"></i>
            {{__('admin.addCategoryDiscount')}}
        </button>
    </div>
    @endif
    <div class="br-section-wrapper">
        @include('Admin.layouts.message')
        <div class="bd bd-gray-300 rounded table-responsive">
            <table class="table table-striped mg-b-0">
                <thead>
                <tr>
                    <th>{{__('admin.nameAttribute')}}</th>
                    @if(auth()->guard('admin')->user()->hasPermissionTo('edit category discount') || auth()->guard('admin')->user()->hasPermissionTo('delete category discount'))
                    <th>{{__('admin.OperationAttribute')}}</th>
                    @endif
                </tr>
                </thead>
                <tbody>
                @foreach($categoryDiscounts as $categoryDiscount)
                    <tr>
                        <td>{{$categoryDiscount->name}}</td>
                        @if(auth()->guard('admin')->user()->hasPermissionTo('edit category discount'))
                        <td>
                            <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#editCategoryDiscount{{$categoryDiscount->id}}">
                                <i class="fa fa-edit"></i>
                                {{__('admin.editCategoryDiscount')}}
                            </button>

                            <!-- Modal -->
                            <div class="modal fade" id="editCategoryDiscount{{$categoryDiscount->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <form class="modal-content" method="post" action="{{route('admin.categories.discounts.update', [$scope, $categoryDiscount->id])}}">
                                        @csrf
                                        @method('put')
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">{{__('admin.editCategoryDiscount')}}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="row">
                                                <label class="col-sm-4 form-control-label">{{__('admin.nameAttribute')}}</label>
                                                <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                                                    <input type="text" name="name" class="form-control" placeholder="{{__('admin.nameAttribute')}}" value="{{$categoryDiscount->name}}" required>
                                                </div>
                                                @include('Admin.layouts.error', ['input' => 'name'])
                                            </div><!-- row -->
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">{{__('admin.closeButton')}} <i class="fa fa-times"></i></button>
                                            <button type="submit" class="btn btn-info btn-sm">{{__('admin.saveButton')}} <i class="fa fa-check"></i></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </td>
                        @endif
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div><!-- bd -->
        {{$categoryDiscounts->links('Admin.layouts.pagination')}}
    </div>

    @if(auth()->guard('admin')->user()->hasPermissionTo('create category discount'))
    <!-- Modal -->
    <div class="modal fade" id="addCategoryDiscount" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form class="modal-content" method="post" action="{{route('admin.categories.discounts.store', $scope)}}">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{__('admin.addCategoryDiscount')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <label class="col-sm-4 form-control-label">{{__('admin.nameAttribute')}} <span class="tx-danger">*</span></label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <input type="text" name="name" class="form-control" placeholder="{{__('admin.nameAttribute')}}" required>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'name'])
                    </div><!-- row -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">{{__('admin.closeButton')}} <i class="fa fa-times"></i></button>
                    <button type="submit" class="btn btn-info btn-sm">{{__('admin.saveButton')}} <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>
    @endif

@endsection