routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'AuthController@viewLoginPage')->name('login');
Route::post('login', 'AuthController@authenticate')->name('authenticate');
Route::get('logout', 'AuthController@logout')->name('logout');

Route::middleware(['admin'])->group(function () {
    Route::get('profile', 'ProfileController@profile')->name('profile');
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::resource('school_info', 'SchoolController');
    Route::resource('admins', 'AdminController');
    Route::resource('academic_years', 'AcademicYearController');
    Route::resource('school_grades', 'SchoolGradeController');
    Route::resource('class_rooms', 'ClassRoomController');
    Route::resource('sections', 'SectionController');
    Route::get('section/{id}', 'SectionController@ajaxSelection');
    Route::resource('students', 'StudentController');
    Route::post('students/payment', 'StudentController@payment')->name('students.payment');
    Route::get('students/payment/receipt/{id}', 'StudentController@payment_receipt')->name('students.payment_receipt');
    Route::post('students/attachment', 'StudentController@attachment')->name('students.attachment');
    Route::post('students/transfer', 'StudentController@transfer')->name('students.transfer');
    Route::resource('category_expenses', 'CategoryExpensesController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('agreements', 'AgreementController');
    Route::get('agreements/getClassRoomPrice/{id}', 'AgreementController@getClassRoomPrice');

    Route::prefix('reports')->name('reports.')->group(function (){
        Route::get('payments', 'ReportController@payments')->name('payments');
        Route::get('payments/receipt/{id}', 'ReportController@payments_receipt')->name('payments.receipt');
        Route::get('expenses', 'ReportController@expenses')->name('expenses');
        Route::get('expenses/receipt/{id}', 'ReportController@expenses_receipt')->name('expenses.receipt');
        Route::get('agreements', 'ReportController@agreements')->name('agreements');
    });

    Route::prefix('employees')->name('employees.')->group(function(){
        Route::resource('sections', 'EmployeeSectionController');
        Route::resource('jobs', 'EmployeeJobController');
        Route::resource('salaries', 'EmployeeSalaryController');
        Route::resource('agreements', 'EmployeeAgreementController');
        Route::resource('allowances', 'EmployeeAllowanceController');
        Route::resource('incentives', 'EmployeeIncentiveController');
        Route::resource('discounts', 'EmployeeDiscountController');
    });
    Route::resource('employees', 'EmployeeController');

    Route::prefix('categories')->name('categories.')->group(function(){
        Route::resource('allowances', 'CategoryAllowanceController');
        Route::resource('incentives', 'CategoryIncentiveController');
        Route::resource('discounts', 'CategoryDiscountController');
    });

    Route::get('set-locale/{locale}', function ($scope, $locale) {
        session()->put('locale', $locale);
        return redirect()->back();
    })->name('locale.setting');
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = [];

    public function job()
    {
        return $this->belongsTo(EmployeeJob::class, 'employee_job_id');
    }

    public function setImageAttribute($value)
    {
        if($value){
            $name = $value->store('employees', 'public');
            $this->attributes['image'] = $name;
        }
    }

    public function getImageAttribute($value)
    {
        if($value){
            return asset('storage/' . $value);
        }
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\AcademicYear;
use App\Models\Employee;
use App\Models\EmployeeJob;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
//    public function __construct()
//    {
//        $this->middleware('permission:show employees')->only('index');
//        $this->middleware('permission:create employee')->only('store');
//        $this->middleware('permission:view employee')->only('show');
//        $this->middleware('permission:edit employee')->only('update');
//        $this->middleware('permission:delete employee')->only('destroy');
//    }

    public function index($scope)
    {
        $employees = Employee::paginate(20);
        $employeeJobs = EmployeeJob::all();
        $academicYears = AcademicYear::select('id', 'year')->get();

        return view('Admin.employees.index', compact('scope', 'employees', 'employeeJobs', 'academicYears'));
    }

    public function store(Request $request, $scope)
    {
        $validate = $this->checkValidation($request);

        Employee::create($validate);

        return back()->with('success', __('admin.storeSuccessMessage'));
    }

    public function show(Request $request, $scope, $id)
    {
       $employee = Employee::find($id);

        return view('Admin.employees.show', compact('scope', 'employee'));
    }

    public function update(Request $request, $scope, $id)
    {
        $validate = $this->checkValidation($request, $id);

        $employee = Employee::where('id', $id)->first();
        $employee->update($validate);
        if($request->image){
            $employee->image = $request->image;
            $employee->save();
        }

        return back()->with('success', __('admin.updateSuccessMessage'));
    }

    public function destroy($id)
    {
        Employee::where('id', $id)->delete();
        return back()->with('success', __('admin.deleteSuccessMessage'));
    }

    public function checkValidation($input, $id = null)
    {
        return $input->validate([
            'academic_year_id' => 'required|exists:academic_years,id',
            'employee_job_id'  => 'required|exists:employee_jobs,id',
            'name'             => 'required|max:190|unique:employees,name,'.$id.',id,employee_job_id,'.$input->employee_job_id.',deleted_at,NULL',
            'phone'            => 'required|max:190|unique:employees,phone,'.$id.',id,employee_job_id,'.$input->employee_job_id.',deleted_at,NULL',
            'email'            => 'required|max:190|unique:employees,email,'.$id.',id,employee_job_id,'.$input->employee_job_id.',deleted_at,NULL',
            'address'          => 'required|max:190',
            'id_number'        => 'required|max:190',
            'expiry_id_number' => 'required|date',
            'nationality'      => 'required|max:190',
            'passport'         => 'required|max:190',
            'expiry_passport'  => 'required|date',
            'image'            => 'sometimes|image',
        ]);
    }
}

resources/views/Admin/employees/incentives/index.blade.php
@extends('Admin.layouts.app')
@section('title') {{__('admin.employeeIncenSideBar')}} @endsection
@section('css') <link rel="stylesheet" href="/admin/css/datepicker.css"> @endsection
@section('content')

    <div class="br-pageheader">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <span class="breadcrumb-item active">{{__('admin.employeeIncenSideBar')}}</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="br-pagetitle">

    </div><!-- d-flex -->
    <!-- Button trigger modal -->
    <div style="padding:15px;float: right">
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#addEmployeeIncentive">
            <i class="fa fa-plus"></i>
            {{__('admin.addEmployeeIncentive')}}
        </button>
    </div>
    <div class="br-section-wrapper">
        @include('Admin.layouts.message')
        <div class="bd bd-gray-300 rounded table-responsive">
            <table class="table table-striped mg-b-0">
                <thead>
                <tr>
                    <th>{{__('admin.categoryIncenSideBar')}}</th>
                    <th>{{__('admin.employeesSideBar')}}</th>
                    <th>{{__('admin.paymentAttribute')}}</th>
                    <th>{{__('admin.dateAttribute')}}</th>
                    <th>{{__('admin.notesAttribute')}}</th>
                    <th>{{__('admin.OperationAttribute')}}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($employeeIncentives as $employeeIncentive)
                    <tr>
                        <td>{{$employeeIncentive->category->name}}</td>
                        <td>{{$employeeIncentive->employee->name}}</td>
                        <td>{{$employeeIncentive->cost}}</td>
                        <td>{{$employeeIncentive->date}}</td>
                        <td>{{$employeeIncentive->notes}}</td>
                        <td>
                            <button type="button" class="btn btn-warning btn-sm" onclick="openModalEditEvent({{$employeeIncentive}})" title="{{__('admin.editEmployeeIncentive')}}">
                                <i class="fa fa-edit"></i>
                            </button>
                            <a target="_blank" class="btn btn-dark btn-sm" href="{{route('admin.employees.incentives.show', [$scope, $employeeIncentive->id])}}" title="{{__('admin.receiptExchangeAttr')}}">
                                <i class="fa fa-print"></i>
                            </a>

                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div><!-- bd -->
        {{$employeeIncentives->links('Admin.layouts.pagination')}}
    </div>

    <!-- Add Modal -->
    <div class="modal fade" id="addEmployeeIncentive" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form class="modal-content" method="post" action="{{route('admin.employees.incentives.store', $scope)}}">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{__('admin.addEmployeeIncentive')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <label class="col-sm-4 form-control-label">{{__('admin.categoryIncenSideBar')}}</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <select name="category_incentive_id" class="form-control">
                                <option selected disabled>{{__('admin.selectCategory')}}</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'category_incentive_id'])
                    </div><!-- row -->
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label">{{__('admin.employeesSideBar')}} <span class="tx-danger">*</span></label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <select id="addSelect" name="employee_id" style="width: 100%">
                                <option selected disabled>{{__('admin.selectEmployee')}}</option>
                                @foreach($employees as $employee)
                                    <option value="{{$employee->id}}">{{$employee->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'employee_id'])
                    </div><!-- row -->
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label">{{__('admin.paymentAttribute')}} <span class="tx-danger">*</span></label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <input type="number" name="cost" class="form-control" placeholder="{{__('admin.paymentAttribute')}}" required>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'cost'])
                    </div><!-- row -->
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label">{{__('admin.dateAttribute')}} <span class="tx-danger">*</span></label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <input type="text" name="date" data-toggle="datepicker" value="{{request()->from ?: now()->format('yy-m-d')}}" autocomplete="off" class="form-control" placeholder="{{__('admin.dateAttribute')}}" required>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'date'])
                    </div><!-- row -->
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label">{{__('admin.notesAttribute')}}</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <textarea rows="3" name="notes" class="form-control" placeholder="{{__('admin.notesAttribute')}}" ></textarea>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'notes'])
                    </div><!-- row -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">{{__('admin.closeButton')}} <i class="fa fa-times"></i></button>
                    <button type="submit" class="btn btn-info btn-sm">{{__('admin.saveButton')}} <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>

    <!-- Edit Modal -->
    <div class="modal fade" id="editEmployeeIncentive" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form class="modal-content" id="edit_form" method="post">
                @csrf
                @method('put')
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{__('admin.editEmployeeIncentive')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <label class="col-sm-4 form-control-label">{{__('admin.categoryIncenSideBar')}}</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <select id="category_incentive_id" name="category_incentive_id" class="form-control">
                                <option selected disabled>{{__('admin.selectCategory')}}</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'category_incentive_id'])
                    </div><!-- row -->
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label">{{__('admin.employeesSideBar')}}</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <select id="editSelect" name="employee_id" style="width: 100%">
                                @foreach($employees as $employee)
                                    <option value="{{$employee->id}}">{{$employee->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'employee_id'])
                    </div><!-- row -->
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label">{{__('admin.paymentAttribute')}}</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <input type="number" id="cost" name="cost" class="form-control" placeholder="{{__('admin.paymentAttribute')}}" required>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'cost'])
                    </div><!-- row -->
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label">{{__('admin.dateAttribute')}}</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <input type="text" id="date" name="date" data-toggle="datepicker" autocomplete="off" class="form-control" placeholder="{{__('admin.dateAttribute')}}" required>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'date'])
                    </div><!-- row -->
                    <div class="row mg-t-20">
                        <label class="col-sm-4 form-control-label">{{__('admin.notesAttribute')}}</label>
                        <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                            <textarea rows="3" id="notes" name="notes" class="form-control" placeholder="{{__('admin.notesAttribute')}}" ></textarea>
                        </div>
                        @include('Admin.layouts.error', ['input' => 'notes'])
                    </div><!-- row -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">{{__('admin.closeButton')}} <i class="fa fa-times"></i></button>
                    <button type="submit" class="btn btn-info btn-sm">{{__('admin.saveButton')}} <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="/admin/js/datepicker.js"></script>

    <script>
        $(function () {
            $("#addSelect").select2({
                dropdownParent: $("#addEmployeeIncentive")
            });

            $("#editSelect").select2({
                dropdownParent: $("#editEmployeeIncentive")
            });

            $('[data-toggle="datepicker"]').datepicker({
                format: 'yyyy-mm-dd',
                autoHide: true,
                zIndex: 2048,
            });
        });

        function openModalEditEvent(employeeIncentive) {

            $('#category_incentive_id').val(employeeIncentive.category_incentive_id);
            $('#editSelect').val(employeeIncentive.employee_id);
            $('#cost').val(employeeIncentive.cost);
            $('#date').val(employeeIncentive.date);
            $('#notes').val(employeeIncentive.notes);

            $('#edit_form').attr('action', '/school/admin/employees/incentives/' + employeeIncentive.id);
            $('#editEmployeeIncentive').modal('show');
        }
    </script>
@endsection