routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'AuthController@viewLoginPage')->name('login');
Route::post('login', 'AuthController@authenticate')->name('authenticate');
Route::get('logout', 'AuthController@logout')->name('logout');

Route::middleware(['admin'])->group(function () {
    Route::get('profile', 'ProfileController@profile')->name('profile');
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::resource('school_info', 'SchoolController');
    Route::resource('admins', 'AdminController');
    Route::resource('academic_years', 'AcademicYearController');
    Route::resource('school_grades', 'SchoolGradeController');
    Route::resource('class_rooms', 'ClassRoomController');
    Route::resource('sections', 'SectionController');
    Route::get('section/{id}', 'SectionController@ajaxSelection');
    Route::resource('students', 'StudentController');
    Route::post('students/payment', 'StudentController@payment')->name('students.payment');
    Route::get('students/payment/receipt/{id}', 'StudentController@payment_receipt')->name('students.payment_receipt');
    Route::post('students/attachment', 'StudentController@attachment')->name('students.attachment');
    Route::post('students/transfer', 'StudentController@transfer')->name('students.transfer');
    Route::resource('category_expenses', 'CategoryExpensesController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('agreements', 'AgreementController');
    Route::get('agreements/getClassRoomPrice/{id}', 'AgreementController@getClassRoomPrice');

    Route::prefix('reports')->name('reports.')->group(function (){
        Route::get('payments', 'ReportController@payments')->name('payments');
        Route::get('payments/receipt/{id}', 'ReportController@payments_receipt')->name('payments.receipt');
        Route::get('expenses', 'ReportController@expenses')->name('expenses');
        Route::get('expenses/receipt/{id}', 'ReportController@expenses_receipt')->name('expenses.receipt');
        Route::get('agreements', 'ReportController@agreements')->name('agreements');
    });

    Route::prefix('employees')->name('employees.')->group(function(){
        Route::resource('sections', 'EmployeeSectionController');
        Route::resource('jobs', 'EmployeeJobController');
        Route::resource('salaries', 'EmployeeSalaryController');
        Route::resource('agreements', 'EmployeeAgreementController');
        Route::resource('allowances', 'EmployeeAllowanceController');
        Route::resource('incentives', 'EmployeeIncentiveController');
        Route::resource('discounts', 'EmployeeDiscountController');
    });
    Route::resource('employees', 'EmployeeController');

    Route::prefix('categories')->name('categories.')->group(function(){
        Route::resource('allowances', 'CategoryAllowanceController');
        Route::resource('incentives', 'CategoryIncentiveController');
        Route::resource('discounts', 'CategoryDiscountController');
    });

    Route::get('set-locale/{locale}', function ($scope, $locale) {
        session()->put('locale', $locale);
        return redirect()->back();
    })->name('locale.setting');
});

app/Models/School.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function setLogoAttribute($value)
    {
        if($value){
            $name = $value->store('school', 'public');
            $this->attributes['logo'] = $name;
        }
    }

    public function getLogoAttribute($value)
    {
        if($value){
            return asset('storage/' . $value);
        }
    }

    public function setHeaderInvoiceImageAttribute($value)
    {
        if($value){
            $name = $value->store('header_invoice_image', 'public');
            $this->attributes['header_invoice_image'] = $name;
        }
    }

    public function getHeaderInvoiceImageAttribute($value)
    {
        if($value){
            return asset('storage/' . $value);
        }
    }

    public function setStampAttribute($value)
    {
        if($value){
            $name = $value->store('stamp', 'public');
            $this->attributes['stamp'] = $name;
        }
    }

    public function getStampAttribute($value)
    {
        if($value){
            return asset('storage/' . $value);
        }
    }
}

app/Http/Controllers/Admin/SchoolController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\School;
use Illuminate\Http\Request;

class SchoolController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:show school')->only('index');
        $this->middleware('permission:create school')->only(['create', 'store']);
        $this->middleware('permission:edit school')->only(['edit', 'update']);
    }

    public function index($scope)
    {
        $school = School::first();
        return view('Admin.school.index', compact('school', 'scope'));
    }

    public function create($scope)
    {
        return view('Admin.school.create', compact('scope'));
    }

    public function store(Request $request, $scope)
    {
        $validate = $this->checkValidation($request);

        School::create($validate);

        return redirect()->route('admin.school_info.index', $scope)->with('success', __('admin.storeSuccessMessage'));
    }

    public function show($id)
    {
        //
    }

    public function edit($scope, $id)
    {
        $school = School::find($id);
        return view('Admin.school.edit', compact('school', 'scope'));
    }

    public function update(Request $request, $id, $scope)
    {
        $validate = $this->checkValidation($request);

        School::first()->update($validate);

        return redirect('/school/admin/school_info')->with('success', __('admin.updateSuccessMessage'));
    }

    public function destroy($id)
    {
        //
    }

    public function checkValidation($input)
    {
        return $input->validate([
            'name'                 => 'required',
            'email'                => 'required',
            'phone'                => 'required',
            'address'              => 'required',
            'logo'                 => 'sometimes|image',
            'header_invoice_image' => 'sometimes|image',
            'stamp'                => 'sometimes|image',
        ]);
    }
}

resources/views/Admin/school/create.blade.php
@extends('Admin.layouts.app')
@section('title') {{__('admin.addSchoolInfo')}} @endsection
@section('content')

    <div class="br-pageheader">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <a class="breadcrumb-item" href="{{route('admin.school_info.index', $scope)}}">{{__('admin.schoolSideBar')}}</a>
            <span class="breadcrumb-item active">{{__('admin.addSchoolInfo')}}</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="br-pagetitle">

    </div><!-- d-flex -->

    <div class="br-section-wrapper">
        @include('Admin.layouts.message')
        <form method="post" action="{{route('admin.school_info.store', $scope)}}" enctype="multipart/form-data">
            @csrf
            <div class="row mg-b-25">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">{{__('admin.nameAttribute')}}: <span class="tx-danger">*</span></label>
                        <input class="form-control" type="text" name="name" placeholder="{{__('admin.nameAttribute')}}" required>
                        @include('Admin.layouts.error', ['input' => 'name'])
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">{{__('admin.emailAttribute')}}: <span class="tx-danger">*</span></label>
                        <input class="form-control" type="email" name="email" placeholder="{{__('admin.emailAttribute')}}" required>
                        @include('Admin.layouts.error', ['input' => 'email'])
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">{{__('admin.phoneAttribute')}}: <span class="tx-danger">*</span></label>
                        <input class="form-control" type="text" name="phone" placeholder="{{__('admin.phoneAttribute')}}" required>
                        @include('Admin.layouts.error', ['input' => 'phone'])
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">{{__('admin.addressAttribute')}}: <span class="tx-danger">*</span></label>
                        <input class="form-control" type="text" name="address" placeholder="{{__('admin.addressAttribute')}}" required>
                        @include('Admin.layouts.error', ['input' => 'address'])
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">{{__('admin.logoAttribute')}}: <span class="tx-danger">*</span></label>
                        <div class="d-flex">
                            <input type="file" name="logo" id="file-1" class="inputfile" required>
                            <label for="file-1" class="tx-white bg-info">
                                <i class="icon ion-ios-upload-outline tx-24"></i>
                                <span>Choose a file...</span>
                            </label>
                        </div><!-- ht-200 -->
                        @include('Admin.layouts.error', ['input' => 'logo'])
                    </div>
                </div><!-- col-4 -->
            </div><!-- row -->

            <div class="modal-footer" style="margin-top: 15px">
                <button type="submit" class="btn btn-info">{{__('admin.saveButton')}} <i class="fa fa-check"></i></button>
            </div>
        </form>
    </div>

@endsection

@section('script')
    <script>
        $(function(){

            'use strict';

            $( '.inputfile' ).each( function()
            {
                var $input	 = $( this ),
                    $label	 = $input.next( 'label' ),
                    labelVal = $label.html();

                $input.on( 'change', function( e )
                {
                    var fileName = '';

                    if( this.files && this.files.length > 1 )
                        fileName = ( this.getAttribute( 'data-multiple-caption' ) || '' ).replace( '{count}', this.files.length );
                    else if( e.target.value )
                        fileName = e.target.value.split( '\\' ).pop();

                    if( fileName )
                        $label.find( 'span' ).html( fileName );
                    else
                        $label.html( labelVal );
                });

                // Firefox bug fix
                $input
                    .on( 'focus', function(){ $input.addClass( 'has-focus' ); })
                    .on( 'blur', function(){ $input.removeClass( 'has-focus' ); });
            });

        });
    </script>
@endsection

resources/views/Admin/school/edit.blade.php
@extends('Admin.layouts.app')
@section('title') {{__('admin.editSchoolInfo')}} @endsection
@section('content')

    <div class="br-pageheader">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <a class="breadcrumb-item" href="{{route('admin.school_info.index', $scope)}}">{{__('admin.schoolSideBar')}}</a>
            <span class="breadcrumb-item active">{{__('admin.editSchoolInfo')}}</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="br-pagetitle">

    </div><!-- d-flex -->

    <div class="br-section-wrapper">
        @include('Admin.layouts.message')
        <form method="post" action="{{route('admin.school_info.update', [$scope, $school->id])}}" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="row mg-b-25">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">{{__('admin.nameAttribute')}}:</label>
                        <input class="form-control" type="text" name="name" value="{{$school->name}}" placeholder="{{__('admin.nameAttribute')}}" required>
                        @include('Admin.layouts.error', ['input' => 'name'])
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">{{__('admin.emailAttribute')}}:</label>
                        <input class="form-control" type="email" name="email" value="{{$school->email}}" placeholder="{{__('admin.emailAttribute')}}" required>
                        @include('Admin.layouts.error', ['input' => 'email'])
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">{{__('admin.phoneAttribute')}}:</label>
                        <input class="form-control" type="text" name="phone" value="{{$school->phone}}" placeholder="{{__('admin.phoneAttribute')}}" required>
                        @include('Admin.layouts.error', ['input' => 'phone'])
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="form-control-label">{{__('admin.addressAttribute')}}:</label>
                        <input class="form-control" type="text" name="address" value="{{$school->address}}" placeholder="{{__('admin.addressAttribute')}}" required>
                        @include('Admin.layouts.error', ['input' => 'address'])
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="row">
                        <div class="form-group col-lg-6">
                            <label class="form-control-label">{{__('admin.logoAttribute')}}:</label>
                            <div class="d-flex">
                                <input type="file" name="logo" id="file-1" class="inputfile">
                                <label for="file-1" class="tx-white bg-info">
                                    <i class="icon ion-ios-upload-outline tx-24"></i>
                                    <span>Choose a file...</span>
                                </label>
                            </div><!-- ht-200 -->
                            @include('Admin.layouts.error', ['input' => 'logo'])
                        </div>
                        <div class="col-lg-6">
                            <img src="{{$school->logo}}" style="width: 100px">
                        </div>
                    </div>
                </div><!-- col-4 -->

                <div class="col-lg-4">
                    <div class="row">
                        <div class="form-group col-lg-6">
                            <label class="form-control-label">{{__('admin.headInvoiceAttribute')}}:</label>
                            <div class="d-flex">
                                <input type="file" name="header_invoice_image" id="file-2" class="inputfile">
                                <label for="file-2" class="tx-white bg-info">
                                    <i class="icon ion-ios-upload-outline tx-24"></i>
                                    <span>Choose a file...</span>
                                </label>
                            </div><!-- ht-200 -->
                            @include('Admin.layouts.error', ['input' => 'header_invoice_image'])
                        </div>
                        <div class="col-lg-6">
                            <img src="{{$school->header_invoice_image}}" style="width: 100px">
                        </div>
                    </div>
                </div><!-- col-4 -->

                <div class="col-lg-4">
                    <div class="row">
                        <div class="form-group col-lg-6">
                            <label class="form-control-label">{{__('admin.stampAttribute')}}:</label>
                            <div class="d-flex">
                                <input type="file" name="stamp" id="file-3" class="inputfile">
                                <label for="file-3" class="tx-white bg-info">
                                    <i class="icon ion-ios-upload-outline tx-24"></i>
                                    <span>Choose a file...</span>
                                </label>
                            </div><!-- ht-200 -->
                            @include('Admin.layouts.error', ['input' => 'stamp'])
                        </div>
                        <div class="col-lg-6">
                            <img src="{{$school->stamp}}" style="width: 100px">
                        </div>
                    </div>
                </div><!-- col-4 -->
            </div><!-- row -->

            <div class="modal-footer" style="margin-top: 15px">
                <button type="submit" class="btn btn-info">{{__('admin.saveButton')}} <i class="fa fa-check"></i></button>
            </div>
        </form>
    </div>

@endsection

@section('script')
    <script>
        $(function(){

            'use strict';

            $( '.inputfile' ).each( function()
            {
                var $input	 = $( this ),
                    $label	 = $input.next( 'label' ),
                    labelVal = $label.html();

                $input.on( 'change', function( e )
                {
                    var fileName = '';

                    if( this.files && this.files.length > 1 )
                        fileName = ( this.getAttribute( 'data-multiple-caption' ) || '' ).replace( '{count}', this.files.length );
                    else if( e.target.value )
                        fileName = e.target.value.split( '\\' ).pop();

                    if( fileName )
                        $label.find( 'span' ).html( fileName );
                    else
                        $label.html( labelVal );
                });

                // Firefox bug fix
                $input
                    .on( 'focus', function(){ $input.addClass( 'has-focus' ); })
                    .on( 'blur', function(){ $input.removeClass( 'has-focus' ); });
            });

        });
    </script>
@endsection

resources/views/Admin/school/index.blade.php
@extends('Admin.layouts.app')
@section('title') {{__('admin.schoolSideBar')}} @endsection
@section('content')

    <div class="br-pageheader">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <span class="breadcrumb-item active">{{__('admin.schoolSideBar')}}</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="br-pagetitle">

    </div><!-- d-flex -->

    <!-- Button trigger modal -->
    @if(auth()->guard('admin')->user()->hasPermissionTo('create school'))
        <div style="padding:15px;float: right">
            @if(!$school)
            <a href="{{route('admin.school_info.create', $scope)}}" class="btn btn-primary btn-sm pull-right">
                <i class="fa fa-plus"></i>
                {{__('admin.addSchoolInfo')}}
            </a>
            @endif
        </div>
    @endif
    <div class="br-section-wrapper">
        @include('Admin.layouts.message')
        <div class="bd bd-gray-300 rounded table-responsive">
            <table class="table table-striped mg-b-0">
                <thead>
                <tr>
                    <th>{{__('admin.nameAttribute')}}</th>
                    <th>{{__('admin.emailAttribute')}}</th>
                    <th>{{__('admin.phoneAttribute')}}</th>
                    <th>{{__('admin.addressAttribute')}}</th>
                    <th>{{__('admin.logoAttribute')}}</th>
                    @if(auth()->guard('admin')->user()->hasPermissionTo('edit school'))
                    <th>{{__('admin.OperationAttribute')}}</th>
                    @endif
                </tr>
                </thead>
                <tbody>
                @if($school)
                <tr>
                    <td>{{$school->name}}</td>
                    <td>{{$school->email}}</td>
                    <td>{{$school->phone}}</td>
                    <td>{{$school->address}}</td>
                    <td><img src="{{$school->logo}}" style="width: 100px"></td>
                    @if(auth()->guard('admin')->user()->hasPermissionTo('edit school'))
                    <td>
                        <a href="{{route('admin.school_info.edit', [$scope, $school->id])}}" class="btn btn-warning btn-sm pull-right">
                            <i class="fa fa-edit"></i>
                            {{__('admin.editSchoolInfo')}}
                        </a>
                    </td>
                    @endif
                </tr>
                @endif
                </tbody>
            </table>
        </div><!-- bd -->
    </div>

@endsection